package com.easyreader.elinkclient.core

object AppConfig {
    const val DEFAULT_BASE_URL = "https://re.dclife.fun:59999/"
    const val DEFAULT_USER_ID = "u1"
    const val CLIENT_TYPE = "eink-android"
    const val API_CONTRACT_VERSION = "2026-06-11"
    const val PREFS_NAME = "elink_client_prefs"
    const val KEY_BASE_URL = "base_url"
    const val KEY_USER_ID = "user_id"
    const val KEY_DEVICE_ID = "device_id"
    const val KEY_READER_FONT_STYLE = "reader_font_style"
    const val KEY_READER_FONT_KEY = "reader_font_key"
    const val KEY_READER_FONT_SIZE = "reader_font_size"
    const val KEY_READER_LINE_SPACING = "reader_line_spacing"
    const val KEY_READER_AUTO_TURN_SPEED = "reader_auto_turn_speed"
    const val KEY_LAST_ACTIVE_BOOK_KEY = "last_active_book_key"
    const val KEY_LAST_ACTIVE_BOOK_NAME = "last_active_book_name"
    const val KEY_LAST_ACTIVE_BOOK_URL = "last_active_book_url"
    const val KEY_LAST_ACTIVE_SOURCE_URL = "last_active_source_url"
    const val KEY_LAST_ACTIVE_CHAPTER_NUMBER = "last_active_chapter_number"
    const val KEY_LAST_ACTIVE_POSITION = "last_active_position"
    const val KEY_PENDING_PROGRESS_QUEUE = "pending_progress_queue"
    const val KEY_SYNC_POLICY = "sync_policy"
    const val KEY_AUTH_TOKEN = "auth_token"
}
